---
title: 'Part B: Descriptive Analysis'
---
```{r}
library(DBI, quietly = T)
library(ggplot2)
library(ggrepel)
library(tibble)
library(dplyr)

# Import the data files from part A
congress <- read.csv("congress-list.csv", stringsAsFactors = F)
post_react <- read.csv("post_react.csv", stringsAsFactors = F)
com_sent <- read.csv("com_sent.csv", stringsAsFactors = F)

# Read the data files into tables of a SQLite database
db <- dbConnect(RSQLite::SQLite(),
                file = "~final-exam-parkerf20/congress.sqlite")

dbWriteTable(db, "congress", congress)
dbWriteTable(db, "post_react", post_react)
dbWriteTable(db, "com_sent", com_sent)

# https://stackoverflow.com/a/33525389 label outliers in a boxplot with mods
is_outlier <- function(x) {
  return(x < quantile(x, 0.15) - 1.5 * IQR(x)
         | x > quantile(x, 0.9909) + 1.5 * IQR(x))
}
```
Calculating proportion of comments that are negative

```{r}
dbGetQuery(db,
  "SELECT (100.0 * SUM(CASE WHEN feel='negative'
  THEN 1 ELSE 0 END) / COUNT(*))
  AS percent_negative FROM com_sent")
```
Variation and proportions of negativity within legislators

```{r}
## Select only negative instances
neg_com <- dbGetQuery(db,
  "SELECT facebook, (100.0 * SUM(CASE WHEN feel='negative'
  THEN 1 ELSE 0 END) / COUNT(*))
  AS percent_negative
  FROM com_sent
  GROUP BY facebook")

# Merge the Facebook and real names from post_react to the SQLite output
neg_com <- distinct(merge(x = neg_com,
                 y = post_react[, c("from_name", "facebook")],
                 by = "facebook"))

# Write into csv for use in part C
write.csv(neg_com, "neg_com.csv")

# Variance of negativity
var(neg_com$percent_negative)

# Graph on a boxplot
neg_box <- neg_com %>%
  rownames_to_column(var = "outlier") %>%
  mutate(is_outlier = ifelse(is_outlier(percent_negative),
                             from_name,
                             as.character(NA)))

box <- ggplot(neg_box, aes(x = factor(0), y = percent_negative))

box +
  geom_boxplot(outlier.colour = "red", outlier.shape = 1) +
  ylab("Percentage of Negativity") +
  ggtitle("Negativity by Legislator") +
  xlab("") +
  theme_classic(base_size = 11) +
  geom_text_repel(aes(label = neg_box$is_outlier),
                  na.rm = T,
                  nudge_y = 0.05,
                  direction = "y")

# geom_text_repel:
#https://www.r-bloggers.com/repel-overlapping-text-labels-in-ggplot2/
```
Evolution of negativity over time

```{r warning=FALSE}
# Negative reactions over time
neg_time <- dbGetQuery(db,
           'SELECT created_time,
           SUM(CASE WHEN feel = "negative" THEN 1 ELSE 0 END)
           AS count_negative
           FROM com_sent
           WHERE created_time >= "2015-01-01"
           GROUP BY created_time')

# Plot the negative reactions over time
neg_time$created_time <- as.Date(neg_time$created_time)
plot(neg_time$created_time, neg_time$count_negative, type = "l",
     xlab = "Time of comment", ylab = "Number of negative sentiments",
     title = "Negative comments over time")

head(neg_time[order(-neg_time$count_negative), ])

```
```{r}
# We can use reactions on post_react to measure negativity

# Question 2
neg_post <- dbGetQuery(db,
  "SELECT from_name, (100.0 * SUM(angry_count + sad_count) /
  SUM(angry_count + sad_count + haha_count + love_count +
  wow_count + likes_count))
  AS percent_negative FROM post_react
  GROUP BY from_name
  ORDER BY percent_negative DESC")

var(neg_post$percent_negative, na.rm = T)

# Question 3
neg_time_post <- dbGetQuery(db,
           'SELECT created_time,
           SUM(angry_count + sad_count)
           AS count_negative
           FROM post_react
           WHERE created_time >= "2015-01-01"
           GROUP BY created_time')

neg_time_post$created_time <- as.Date(neg_time_post$created_time)

head(neg_time_post[order(-neg_time_post$count_negative), ])

plot(neg_time_post$created_time, neg_time_post$count_negative, type = "l",
     xlab = "Time of post", ylab = "Number of negative reactions",
     title = "Negative reactions over time")

dbDisconnect(db)

lintr::lint("B-descriptive-analysis.Rmd")
```


